// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: goals.sql

package dbgen

import (
	"context"
)

const getAllMonthlyGoals = `-- name: GetAllMonthlyGoals :many
SELECT id, year, month, target_amount, created_at FROM monthly_goals ORDER BY year DESC, month DESC
`

func (q *Queries) GetAllMonthlyGoals(ctx context.Context) ([]MonthlyGoal, error) {
	rows, err := q.db.QueryContext(ctx, getAllMonthlyGoals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonthlyGoal{}
	for rows.Next() {
		var i MonthlyGoal
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.Month,
			&i.TargetAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyGoal = `-- name: GetMonthlyGoal :one
SELECT id, year, month, target_amount, created_at FROM monthly_goals WHERE year = ? AND month = ?
`

type GetMonthlyGoalParams struct {
	Year  int64 `json:"year"`
	Month int64 `json:"month"`
}

func (q *Queries) GetMonthlyGoal(ctx context.Context, arg GetMonthlyGoalParams) (MonthlyGoal, error) {
	row := q.db.QueryRowContext(ctx, getMonthlyGoal, arg.Year, arg.Month)
	var i MonthlyGoal
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Month,
		&i.TargetAmount,
		&i.CreatedAt,
	)
	return i, err
}

const setMonthlyGoal = `-- name: SetMonthlyGoal :one
INSERT INTO monthly_goals (year, month, target_amount)
VALUES (?, ?, ?)
ON CONFLICT(year, month) DO UPDATE SET target_amount = excluded.target_amount
RETURNING id, year, month, target_amount, created_at
`

type SetMonthlyGoalParams struct {
	Year         int64 `json:"year"`
	Month        int64 `json:"month"`
	TargetAmount int64 `json:"target_amount"`
}

func (q *Queries) SetMonthlyGoal(ctx context.Context, arg SetMonthlyGoalParams) (MonthlyGoal, error) {
	row := q.db.QueryRowContext(ctx, setMonthlyGoal, arg.Year, arg.Month, arg.TargetAmount)
	var i MonthlyGoal
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Month,
		&i.TargetAmount,
		&i.CreatedAt,
	)
	return i, err
}
