// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger.sql

package dbgen

import (
	"context"
	"time"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards (name, billing_start_day, billing_end_day) 
VALUES (?, ?, ?)
RETURNING id, name, billing_start_day, billing_end_day, created_at
`

type CreateCardParams struct {
	Name            string `json:"name"`
	BillingStartDay int64  `json:"billing_start_day"`
	BillingEndDay   int64  `json:"billing_end_day"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, createCard, arg.Name, arg.BillingStartDay, arg.BillingEndDay)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BillingStartDay,
		&i.BillingEndDay,
		&i.CreatedAt,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, keywords) VALUES (?, ?)
RETURNING id, name, keywords, created_at
`

type CreateCategoryParams struct {
	Name     string `json:"name"`
	Keywords string `json:"keywords"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.Name, arg.Keywords)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Keywords,
		&i.CreatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    card_id, category_id, transaction_date, description, amount,
    is_installment, installment_months, installment_current, original_amount, is_cancelled
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, card_id, category_id, transaction_date, description, amount, is_installment, installment_months, installment_current, original_amount, created_at, is_cancelled
`

type CreateTransactionParams struct {
	CardID             int64     `json:"card_id"`
	CategoryID         *int64    `json:"category_id"`
	TransactionDate    time.Time `json:"transaction_date"`
	Description        string    `json:"description"`
	Amount             int64     `json:"amount"`
	IsInstallment      int64     `json:"is_installment"`
	InstallmentMonths  *int64    `json:"installment_months"`
	InstallmentCurrent *int64    `json:"installment_current"`
	OriginalAmount     *int64    `json:"original_amount"`
	IsCancelled        int64     `json:"is_cancelled"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.CardID,
		arg.CategoryID,
		arg.TransactionDate,
		arg.Description,
		arg.Amount,
		arg.IsInstallment,
		arg.InstallmentMonths,
		arg.InstallmentCurrent,
		arg.OriginalAmount,
		arg.IsCancelled,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.CategoryID,
		&i.TransactionDate,
		&i.Description,
		&i.Amount,
		&i.IsInstallment,
		&i.InstallmentMonths,
		&i.InstallmentCurrent,
		&i.OriginalAmount,
		&i.CreatedAt,
		&i.IsCancelled,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM cards WHERE id = ?
`

func (q *Queries) DeleteCard(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCard, id)
	return err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions WHERE id = ?
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const getAllCards = `-- name: GetAllCards :many
SELECT id, name, billing_start_day, billing_end_day, created_at FROM cards ORDER BY name
`

func (q *Queries) GetAllCards(ctx context.Context) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getAllCards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BillingStartDay,
			&i.BillingEndDay,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCategories = `-- name: GetAllCategories :many
SELECT id, name, keywords, created_at FROM categories ORDER BY name
`

func (q *Queries) GetAllCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Keywords,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTransactions = `-- name: GetAllTransactions :many
SELECT t.id, t.card_id, t.category_id, t.transaction_date, t.description, t.amount, t.is_installment, t.installment_months, t.installment_current, t.original_amount, t.created_at, t.is_cancelled, c.name as card_name, cat.name as category_name
FROM transactions t
JOIN cards c ON t.card_id = c.id
LEFT JOIN categories cat ON t.category_id = cat.id
ORDER BY t.transaction_date DESC
`

type GetAllTransactionsRow struct {
	ID                 int64     `json:"id"`
	CardID             int64     `json:"card_id"`
	CategoryID         *int64    `json:"category_id"`
	TransactionDate    time.Time `json:"transaction_date"`
	Description        string    `json:"description"`
	Amount             int64     `json:"amount"`
	IsInstallment      int64     `json:"is_installment"`
	InstallmentMonths  *int64    `json:"installment_months"`
	InstallmentCurrent *int64    `json:"installment_current"`
	OriginalAmount     *int64    `json:"original_amount"`
	CreatedAt          time.Time `json:"created_at"`
	IsCancelled        int64     `json:"is_cancelled"`
	CardName           string    `json:"card_name"`
	CategoryName       *string   `json:"category_name"`
}

func (q *Queries) GetAllTransactions(ctx context.Context) ([]GetAllTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllTransactionsRow{}
	for rows.Next() {
		var i GetAllTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.CategoryID,
			&i.TransactionDate,
			&i.Description,
			&i.Amount,
			&i.IsInstallment,
			&i.InstallmentMonths,
			&i.InstallmentCurrent,
			&i.OriginalAmount,
			&i.CreatedAt,
			&i.IsCancelled,
			&i.CardName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCard = `-- name: GetCard :one
SELECT id, name, billing_start_day, billing_end_day, created_at FROM cards WHERE id = ?
`

func (q *Queries) GetCard(ctx context.Context, id int64) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCard, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BillingStartDay,
		&i.BillingEndDay,
		&i.CreatedAt,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, keywords, created_at FROM categories WHERE id = ?
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Keywords,
		&i.CreatedAt,
	)
	return i, err
}

const getSumByCard = `-- name: GetSumByCard :many
DESC;

SELECT 
    c.name as card_name,
    c.id as card_id,
    SUM(t.amount) as total_amount,
    COUNT(*) as count
FROM transactions t
JOIN cards c ON t.card_id = c.id
WHERE substr(t.transaction_date, 1, 10) >= ? AND substr(t.transaction_date, 1, 10) < ?
GROUP BY t.card_id
ORDER BY total_amoun
`

type GetSumByCardParams struct {
	TransactionDate   time.Time `json:"transaction_date"`
	TransactionDate_2 time.Time `json:"transaction_date_2"`
}

type GetSumByCardRow struct {
	CardName    string   `json:"card_name"`
	CardID      int64    `json:"card_id"`
	TotalAmount *float64 `json:"total_amount"`
	Count       int64    `json:"count"`
}

func (q *Queries) GetSumByCard(ctx context.Context, arg GetSumByCardParams) ([]GetSumByCardRow, error) {
	rows, err := q.db.QueryContext(ctx, getSumByCard, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSumByCardRow{}
	for rows.Next() {
		var i GetSumByCardRow
		if err := rows.Scan(
			&i.CardName,
			&i.CardID,
			&i.TotalAmount,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSumByCategory = `-- name: GetSumByCategory :many
SELECT 
    COALESCE(cat.name, '미분류') as category_name,
    SUM(t.amount) as total_amount,
    COUNT(*) as count
FROM transactions t
LEFT JOIN categories cat ON t.category_id = cat.id
WHERE substr(t.transaction_date, 1, 10) >= ? AND substr(t.transaction_date, 1, 10) < ?
GROUP BY t.category_id
ORDER BY total_amoun
`

type GetSumByCategoryParams struct {
	TransactionDate   time.Time `json:"transaction_date"`
	TransactionDate_2 time.Time `json:"transaction_date_2"`
}

type GetSumByCategoryRow struct {
	CategoryName string   `json:"category_name"`
	TotalAmount  *float64 `json:"total_amount"`
	Count        int64    `json:"count"`
}

func (q *Queries) GetSumByCategory(ctx context.Context, arg GetSumByCategoryParams) ([]GetSumByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getSumByCategory, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSumByCategoryRow{}
	for rows.Next() {
		var i GetSumByCategoryRow
		if err := rows.Scan(&i.CategoryName, &i.TotalAmount, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, card_id, category_id, transaction_date, description, amount, is_installment, installment_months, installment_current, original_amount, created_at, is_cancelled FROM transactions WHERE id = ?
`

func (q *Queries) GetTransaction(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.CategoryID,
		&i.TransactionDate,
		&i.Description,
		&i.Amount,
		&i.IsInstallment,
		&i.InstallmentMonths,
		&i.InstallmentCurrent,
		&i.OriginalAmount,
		&i.CreatedAt,
		&i.IsCancelled,
	)
	return i, err
}

const getTransactionsByCardAndDateRange = `-- name: GetTransactionsByCardAndDateRange :many
SELECT t.id, t.card_id, t.category_id, t.transaction_date, t.description, t.amount, t.is_installment, t.installment_months, t.installment_current, t.original_amount, t.created_at, t.is_cancelled, c.name as card_name, cat.name as category_name
FROM transactions t
JOIN cards c ON t.card_id = c.id
LEFT JOIN categories cat ON t.category_id = cat.id
WHERE t.card_id = ? AND t.transaction_date >= ? AND t.transaction_date < ?
ORDER BY t.transaction_date DESC
`

type GetTransactionsByCardAndDateRangeParams struct {
	CardID            int64     `json:"card_id"`
	TransactionDate   time.Time `json:"transaction_date"`
	TransactionDate_2 time.Time `json:"transaction_date_2"`
}

type GetTransactionsByCardAndDateRangeRow struct {
	ID                 int64     `json:"id"`
	CardID             int64     `json:"card_id"`
	CategoryID         *int64    `json:"category_id"`
	TransactionDate    time.Time `json:"transaction_date"`
	Description        string    `json:"description"`
	Amount             int64     `json:"amount"`
	IsInstallment      int64     `json:"is_installment"`
	InstallmentMonths  *int64    `json:"installment_months"`
	InstallmentCurrent *int64    `json:"installment_current"`
	OriginalAmount     *int64    `json:"original_amount"`
	CreatedAt          time.Time `json:"created_at"`
	IsCancelled        int64     `json:"is_cancelled"`
	CardName           string    `json:"card_name"`
	CategoryName       *string   `json:"category_name"`
}

func (q *Queries) GetTransactionsByCardAndDateRange(ctx context.Context, arg GetTransactionsByCardAndDateRangeParams) ([]GetTransactionsByCardAndDateRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByCardAndDateRange, arg.CardID, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTransactionsByCardAndDateRangeRow{}
	for rows.Next() {
		var i GetTransactionsByCardAndDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.CategoryID,
			&i.TransactionDate,
			&i.Description,
			&i.Amount,
			&i.IsInstallment,
			&i.InstallmentMonths,
			&i.InstallmentCurrent,
			&i.OriginalAmount,
			&i.CreatedAt,
			&i.IsCancelled,
			&i.CardName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByDateRange = `-- name: GetTransactionsByDateRange :many
SELECT t.id, t.card_id, t.category_id, t.transaction_date, t.description, t.amount, t.is_installment, t.installment_months, t.installment_current, t.original_amount, t.created_at, t.is_cancelled, c.name as card_name, cat.name as category_name
FROM transactions t
JOIN cards c ON t.card_id = c.id
LEFT JOIN categories cat ON t.category_id = cat.id
WHERE t.transaction_date >= ? AND t.transaction_date < ?
ORDER BY t.transaction_date DESC
`

type GetTransactionsByDateRangeParams struct {
	TransactionDate   time.Time `json:"transaction_date"`
	TransactionDate_2 time.Time `json:"transaction_date_2"`
}

type GetTransactionsByDateRangeRow struct {
	ID                 int64     `json:"id"`
	CardID             int64     `json:"card_id"`
	CategoryID         *int64    `json:"category_id"`
	TransactionDate    time.Time `json:"transaction_date"`
	Description        string    `json:"description"`
	Amount             int64     `json:"amount"`
	IsInstallment      int64     `json:"is_installment"`
	InstallmentMonths  *int64    `json:"installment_months"`
	InstallmentCurrent *int64    `json:"installment_current"`
	OriginalAmount     *int64    `json:"original_amount"`
	CreatedAt          time.Time `json:"created_at"`
	IsCancelled        int64     `json:"is_cancelled"`
	CardName           string    `json:"card_name"`
	CategoryName       *string   `json:"category_name"`
}

func (q *Queries) GetTransactionsByDateRange(ctx context.Context, arg GetTransactionsByDateRangeParams) ([]GetTransactionsByDateRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByDateRange, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTransactionsByDateRangeRow{}
	for rows.Next() {
		var i GetTransactionsByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.CategoryID,
			&i.TransactionDate,
			&i.Description,
			&i.Amount,
			&i.IsInstallment,
			&i.InstallmentMonths,
			&i.InstallmentCurrent,
			&i.OriginalAmount,
			&i.CreatedAt,
			&i.IsCancelled,
			&i.CardName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCard = `-- name: UpdateCard :exec
UPDATE cards SET name = ?, billing_start_day = ?, billing_end_day = ? WHERE id = ?
`

type UpdateCardParams struct {
	Name            string `json:"name"`
	BillingStartDay int64  `json:"billing_start_day"`
	BillingEndDay   int64  `json:"billing_end_day"`
	ID              int64  `json:"id"`
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) error {
	_, err := q.db.ExecContext(ctx, updateCard,
		arg.Name,
		arg.BillingStartDay,
		arg.BillingEndDay,
		arg.ID,
	)
	return err
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories SET name = ?, keywords = ? WHERE id = ?
`

type UpdateCategoryParams struct {
	Name     string `json:"name"`
	Keywords string `json:"keywords"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory, arg.Name, arg.Keywords, arg.ID)
	return err
}

const updateTransaction = `-- name: UpdateTransaction :exec
UPDATE transactions SET 
    card_id = ?, category_id = ?, transaction_date = ?, description = ?,
    amount = ?, is_installment = ?, installment_months = ?, 
    installment_current = ?, original_amount = ?, is_cancelled = ?
WHERE id = ?
`

type UpdateTransactionParams struct {
	CardID             int64     `json:"card_id"`
	CategoryID         *int64    `json:"category_id"`
	TransactionDate    time.Time `json:"transaction_date"`
	Description        string    `json:"description"`
	Amount             int64     `json:"amount"`
	IsInstallment      int64     `json:"is_installment"`
	InstallmentMonths  *int64    `json:"installment_months"`
	InstallmentCurrent *int64    `json:"installment_current"`
	OriginalAmount     *int64    `json:"original_amount"`
	IsCancelled        int64     `json:"is_cancelled"`
	ID                 int64     `json:"id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) error {
	_, err := q.db.ExecContext(ctx, updateTransaction,
		arg.CardID,
		arg.CategoryID,
		arg.TransactionDate,
		arg.Description,
		arg.Amount,
		arg.IsInstallment,
		arg.InstallmentMonths,
		arg.InstallmentCurrent,
		arg.OriginalAmount,
		arg.IsCancelled,
		arg.ID,
	)
	return err
}
