// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type Card struct {
	ID              int64     `json:"id"`
	Name            string    `json:"name"`
	BillingStartDay int64     `json:"billing_start_day"`
	BillingEndDay   int64     `json:"billing_end_day"`
	CreatedAt       time.Time `json:"created_at"`
}

type Category struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Keywords  string    `json:"keywords"`
	CreatedAt time.Time `json:"created_at"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type Transaction struct {
	ID                 int64     `json:"id"`
	CardID             int64     `json:"card_id"`
	CategoryID         *int64    `json:"category_id"`
	TransactionDate    time.Time `json:"transaction_date"`
	Description        string    `json:"description"`
	Amount             int64     `json:"amount"`
	IsInstallment      int64     `json:"is_installment"`
	InstallmentMonths  *int64    `json:"installment_months"`
	InstallmentCurrent *int64    `json:"installment_current"`
	OriginalAmount     *int64    `json:"original_amount"`
	CreatedAt          time.Time `json:"created_at"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}
