// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type ApiKey struct {
	ID         int64      `json:"id"`
	KeyHash    string     `json:"key_hash"`
	Name       string     `json:"name"`
	IsActive   int64      `json:"is_active"`
	LastUsedAt *time.Time `json:"last_used_at"`
	CreatedAt  time.Time  `json:"created_at"`
}

type AppSetting struct {
	ID        int64     `json:"id"`
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}

type AssetType struct {
	ID           int64     `json:"id"`
	Name         string    `json:"name"`
	Type         string    `json:"type"`
	IsCard       int64     `json:"is_card"`
	CardID       *int64    `json:"card_id"`
	IsRecurring  int64     `json:"is_recurring"`
	DisplayOrder int64     `json:"display_order"`
	IsSystem     int64     `json:"is_system"`
	CreatedAt    time.Time `json:"created_at"`
}

type Card struct {
	ID              int64     `json:"id"`
	Name            string    `json:"name"`
	BillingStartDay int64     `json:"billing_start_day"`
	BillingEndDay   int64     `json:"billing_end_day"`
	CreatedAt       time.Time `json:"created_at"`
}

type Category struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Keywords  string    `json:"keywords"`
	CreatedAt time.Time `json:"created_at"`
}

type CategoryMapping struct {
	ID                    int64     `json:"id"`
	Description           string    `json:"description"`
	NormalizedDescription string    `json:"normalized_description"`
	CategoryID            int64     `json:"category_id"`
	UsageCount            int64     `json:"usage_count"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
}

type IncomeCategory struct {
	ID           int64     `json:"id"`
	Name         string    `json:"name"`
	DisplayOrder int64     `json:"display_order"`
	CreatedAt    time.Time `json:"created_at"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type MonthlyGoal struct {
	ID           int64     `json:"id"`
	Year         int64     `json:"year"`
	Month        int64     `json:"month"`
	TargetAmount int64     `json:"target_amount"`
	CreatedAt    time.Time `json:"created_at"`
}

type RecurringSchedule struct {
	ID                int64     `json:"id"`
	TxType            string    `json:"tx_type"`
	AssetTypeID       int64     `json:"asset_type_id"`
	CategoryID        *int64    `json:"category_id"`
	IncomeCategoryID  *int64    `json:"income_category_id"`
	Description       string    `json:"description"`
	Amount            int64     `json:"amount"`
	DayOfMonth        int64     `json:"day_of_month"`
	Memo              *string   `json:"memo"`
	IsActive          int64     `json:"is_active"`
	LastGeneratedDate *string   `json:"last_generated_date"`
	CreatedAt         time.Time `json:"created_at"`
}

type SmsLog struct {
	ID                int64     `json:"id"`
	RawText           string    `json:"raw_text"`
	ParsedCardName    *string   `json:"parsed_card_name"`
	ParsedAmount      *int64    `json:"parsed_amount"`
	ParsedDescription *string   `json:"parsed_description"`
	ParsedDate        *string   `json:"parsed_date"`
	TransactionID     *int64    `json:"transaction_id"`
	Status            string    `json:"status"`
	ErrorMessage      *string   `json:"error_message"`
	CreatedAt         time.Time `json:"created_at"`
}

type SmsMappingRule struct {
	ID          int64     `json:"id"`
	RuleType    string    `json:"rule_type"`
	Keyword     string    `json:"keyword"`
	AssetTypeID *int64    `json:"asset_type_id"`
	TxType      *string   `json:"tx_type"`
	Description *string   `json:"description"`
	Priority    int64     `json:"priority"`
	IsActive    int64     `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
}

type Transaction struct {
	ID                  int64     `json:"id"`
	CardID              *int64    `json:"card_id"`
	CategoryID          *int64    `json:"category_id"`
	TransactionDate     time.Time `json:"transaction_date"`
	Description         string    `json:"description"`
	Amount              int64     `json:"amount"`
	IsInstallment       int64     `json:"is_installment"`
	InstallmentMonths   *int64    `json:"installment_months"`
	InstallmentCurrent  *int64    `json:"installment_current"`
	OriginalAmount      *int64    `json:"original_amount"`
	CreatedAt           time.Time `json:"created_at"`
	IsCancelled         int64     `json:"is_cancelled"`
	Memo                *string   `json:"memo"`
	TxType              string    `json:"tx_type"`
	AssetTypeID         *int64    `json:"asset_type_id"`
	IncomeCategoryID    *int64    `json:"income_category_id"`
	RecurringScheduleID *int64    `json:"recurring_schedule_id"`
	IsRecurring         int64     `json:"is_recurring"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}
