// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type ApiKey struct {
	ID         int64      `json:"id"`
	KeyHash    string     `json:"key_hash"`
	Name       string     `json:"name"`
	IsActive   int64      `json:"is_active"`
	LastUsedAt *time.Time `json:"last_used_at"`
	CreatedAt  time.Time  `json:"created_at"`
}

type Card struct {
	ID              int64     `json:"id"`
	Name            string    `json:"name"`
	BillingStartDay int64     `json:"billing_start_day"`
	BillingEndDay   int64     `json:"billing_end_day"`
	CreatedAt       time.Time `json:"created_at"`
}

type Category struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Keywords  string    `json:"keywords"`
	CreatedAt time.Time `json:"created_at"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type MonthlyGoal struct {
	ID           int64     `json:"id"`
	Year         int64     `json:"year"`
	Month        int64     `json:"month"`
	TargetAmount int64     `json:"target_amount"`
	CreatedAt    time.Time `json:"created_at"`
}

type SmsLog struct {
	ID                int64     `json:"id"`
	RawText           string    `json:"raw_text"`
	ParsedCardName    *string   `json:"parsed_card_name"`
	ParsedAmount      *int64    `json:"parsed_amount"`
	ParsedDescription *string   `json:"parsed_description"`
	ParsedDate        *string   `json:"parsed_date"`
	TransactionID     *int64    `json:"transaction_id"`
	Status            string    `json:"status"`
	ErrorMessage      *string   `json:"error_message"`
	CreatedAt         time.Time `json:"created_at"`
}

type Transaction struct {
	ID                 int64     `json:"id"`
	CardID             int64     `json:"card_id"`
	CategoryID         *int64    `json:"category_id"`
	TransactionDate    time.Time `json:"transaction_date"`
	Description        string    `json:"description"`
	Amount             int64     `json:"amount"`
	IsInstallment      int64     `json:"is_installment"`
	InstallmentMonths  *int64    `json:"installment_months"`
	InstallmentCurrent *int64    `json:"installment_current"`
	OriginalAmount     *int64    `json:"original_amount"`
	CreatedAt          time.Time `json:"created_at"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}
