// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shortcut.sql

package dbgen

import (
	"context"
	"time"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (key_hash, name) VALUES (?, ?)
RETURNING id, key_hash, name, is_active, last_used_at, created_at
`

type CreateAPIKeyParams struct {
	KeyHash string `json:"key_hash"`
	Name    string `json:"name"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey, arg.KeyHash, arg.Name)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.Name,
		&i.IsActive,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSMSLog = `-- name: CreateSMSLog :one
INSERT INTO sms_logs (
    raw_text, parsed_card_name, parsed_amount, parsed_description,
    parsed_date, transaction_id, status, error_message
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, raw_text, parsed_card_name, parsed_amount, parsed_description, parsed_date, transaction_id, status, error_message, created_at
`

type CreateSMSLogParams struct {
	RawText           string  `json:"raw_text"`
	ParsedCardName    *string `json:"parsed_card_name"`
	ParsedAmount      *int64  `json:"parsed_amount"`
	ParsedDescription *string `json:"parsed_description"`
	ParsedDate        *string `json:"parsed_date"`
	TransactionID     *int64  `json:"transaction_id"`
	Status            string  `json:"status"`
	ErrorMessage      *string `json:"error_message"`
}

func (q *Queries) CreateSMSLog(ctx context.Context, arg CreateSMSLogParams) (SmsLog, error) {
	row := q.db.QueryRowContext(ctx, createSMSLog,
		arg.RawText,
		arg.ParsedCardName,
		arg.ParsedAmount,
		arg.ParsedDescription,
		arg.ParsedDate,
		arg.TransactionID,
		arg.Status,
		arg.ErrorMessage,
	)
	var i SmsLog
	err := row.Scan(
		&i.ID,
		&i.RawText,
		&i.ParsedCardName,
		&i.ParsedAmount,
		&i.ParsedDescription,
		&i.ParsedDate,
		&i.TransactionID,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateAPIKey = `-- name: DeactivateAPIKey :exec
UPDATE api_keys SET is_active = 0 WHERE id = ?
`

func (q *Queries) DeactivateAPIKey(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deactivateAPIKey, id)
	return err
}

const deleteAllSMSLogs = `-- name: DeleteAllSMSLogs :exec
DELETE FROM sms_logs
`

func (q *Queries) DeleteAllSMSLogs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllSMSLogs)
	return err
}

const deleteSMSLog = `-- name: DeleteSMSLog :exec
DELETE FROM sms_logs WHERE id = ?
`

func (q *Queries) DeleteSMSLog(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSMSLog, id)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, key_hash, name, is_active, last_used_at, created_at FROM api_keys WHERE key_hash = ? AND is_active = 1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.Name,
		&i.IsActive,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAllAPIKeys = `-- name: GetAllAPIKeys :many
SELECT id, name, is_active, last_used_at, created_at FROM api_keys ORDER BY created_at DESC
`

type GetAllAPIKeysRow struct {
	ID         int64      `json:"id"`
	Name       string     `json:"name"`
	IsActive   int64      `json:"is_active"`
	LastUsedAt *time.Time `json:"last_used_at"`
	CreatedAt  time.Time  `json:"created_at"`
}

func (q *Queries) GetAllAPIKeys(ctx context.Context) ([]GetAllAPIKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllAPIKeysRow{}
	for rows.Next() {
		var i GetAllAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardByName = `-- name: GetCardByName :one
SELECT id, name, billing_start_day, billing_end_day, created_at FROM cards WHERE name = ?
`

func (q *Queries) GetCardByName(ctx context.Context, name string) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCardByName, name)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BillingStartDay,
		&i.BillingEndDay,
		&i.CreatedAt,
	)
	return i, err
}

const getSMSLogs = `-- name: GetSMSLogs :many
SELECT id, raw_text, parsed_card_name, parsed_amount, parsed_description, parsed_date, transaction_id, status, error_message, created_at FROM sms_logs ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) GetSMSLogs(ctx context.Context, limit int64) ([]SmsLog, error) {
	rows, err := q.db.QueryContext(ctx, getSMSLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SmsLog{}
	for rows.Next() {
		var i SmsLog
		if err := rows.Scan(
			&i.ID,
			&i.RawText,
			&i.ParsedCardName,
			&i.ParsedAmount,
			&i.ParsedDescription,
			&i.ParsedDate,
			&i.TransactionID,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateAPIKeyLastUsed, id)
	return err
}

const updateSMSLogStatus = `-- name: UpdateSMSLogStatus :exec
UPDATE sms_logs SET status = ?, transaction_id = ?, error_message = ? WHERE id = ?
`

type UpdateSMSLogStatusParams struct {
	Status        string  `json:"status"`
	TransactionID *int64  `json:"transaction_id"`
	ErrorMessage  *string `json:"error_message"`
	ID            int64   `json:"id"`
}

func (q *Queries) UpdateSMSLogStatus(ctx context.Context, arg UpdateSMSLogStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSMSLogStatus,
		arg.Status,
		arg.TransactionID,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}
