// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sms_mapping_rules.sql

package dbgen

import (
	"context"
)

const createSMSMappingRule = `-- name: CreateSMSMappingRule :one
INSERT INTO sms_mapping_rules (rule_type, keyword, asset_type_id, tx_type, description, priority)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, rule_type, keyword, asset_type_id, tx_type, description, priority, is_active, created_at
`

type CreateSMSMappingRuleParams struct {
	RuleType    string  `json:"rule_type"`
	Keyword     string  `json:"keyword"`
	AssetTypeID *int64  `json:"asset_type_id"`
	TxType      *string `json:"tx_type"`
	Description *string `json:"description"`
	Priority    int64   `json:"priority"`
}

func (q *Queries) CreateSMSMappingRule(ctx context.Context, arg CreateSMSMappingRuleParams) (SmsMappingRule, error) {
	row := q.db.QueryRowContext(ctx, createSMSMappingRule,
		arg.RuleType,
		arg.Keyword,
		arg.AssetTypeID,
		arg.TxType,
		arg.Description,
		arg.Priority,
	)
	var i SmsMappingRule
	err := row.Scan(
		&i.ID,
		&i.RuleType,
		&i.Keyword,
		&i.AssetTypeID,
		&i.TxType,
		&i.Description,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSMSMappingRule = `-- name: DeleteSMSMappingRule :exec
DELETE FROM sms_mapping_rules WHERE id = ?
`

func (q *Queries) DeleteSMSMappingRule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSMSMappingRule, id)
	return err
}

const getAllCardsWithKeywords = `-- name: GetAllCardsWithKeywords :many
SELECT c.id, c.name, at.id as asset_type_id FROM cards c
LEFT JOIN asset_types at ON at.card_id = c.id AND at.is_card = 1
`

type GetAllCardsWithKeywordsRow struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	AssetTypeID *int64 `json:"asset_type_id"`
}

func (q *Queries) GetAllCardsWithKeywords(ctx context.Context) ([]GetAllCardsWithKeywordsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllCardsWithKeywords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllCardsWithKeywordsRow{}
	for rows.Next() {
		var i GetAllCardsWithKeywordsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.AssetTypeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSMSMappingRules = `-- name: GetSMSMappingRules :many
SELECT id, rule_type, keyword, asset_type_id, tx_type, description, priority, is_active, created_at FROM sms_mapping_rules WHERE is_active = 1 ORDER BY priority DESC
`

func (q *Queries) GetSMSMappingRules(ctx context.Context) ([]SmsMappingRule, error) {
	rows, err := q.db.QueryContext(ctx, getSMSMappingRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SmsMappingRule{}
	for rows.Next() {
		var i SmsMappingRule
		if err := rows.Scan(
			&i.ID,
			&i.RuleType,
			&i.Keyword,
			&i.AssetTypeID,
			&i.TxType,
			&i.Description,
			&i.Priority,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSMSMappingRulesByType = `-- name: GetSMSMappingRulesByType :many
SELECT id, rule_type, keyword, asset_type_id, tx_type, description, priority, is_active, created_at FROM sms_mapping_rules WHERE rule_type = ? AND is_active = 1 ORDER BY priority DESC
`

func (q *Queries) GetSMSMappingRulesByType(ctx context.Context, ruleType string) ([]SmsMappingRule, error) {
	rows, err := q.db.QueryContext(ctx, getSMSMappingRulesByType, ruleType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SmsMappingRule{}
	for rows.Next() {
		var i SmsMappingRule
		if err := rows.Scan(
			&i.ID,
			&i.RuleType,
			&i.Keyword,
			&i.AssetTypeID,
			&i.TxType,
			&i.Description,
			&i.Priority,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSMSMappingRule = `-- name: UpdateSMSMappingRule :exec
UPDATE sms_mapping_rules SET keyword = ?, asset_type_id = ?, tx_type = ?, description = ?, priority = ? WHERE id = ?
`

type UpdateSMSMappingRuleParams struct {
	Keyword     string  `json:"keyword"`
	AssetTypeID *int64  `json:"asset_type_id"`
	TxType      *string `json:"tx_type"`
	Description *string `json:"description"`
	Priority    int64   `json:"priority"`
	ID          int64   `json:"id"`
}

func (q *Queries) UpdateSMSMappingRule(ctx context.Context, arg UpdateSMSMappingRuleParams) error {
	_, err := q.db.ExecContext(ctx, updateSMSMappingRule,
		arg.Keyword,
		arg.AssetTypeID,
		arg.TxType,
		arg.Description,
		arg.Priority,
		arg.ID,
	)
	return err
}
